dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --no-watch

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: 
        - npm run test -- --no-watch
    - stage: build
      script: 
        - npm run build -- --prod
          ls 